name: Docker Testing

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Test Docker Container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-docker-image -f Configs/Dockerfile .

    - name: Run tests
      run: docker run my-docker-image npm test