version: '3'

services:
  apache:
    image: custom-apache-image
    container_name: apache2
    ports:
      - "8000:8000"
    deploy:
      mode: global
    volumes:
      - /apache_conf/apache.conf:/usr/local/apache2/conf/httpd.conf
      - /apache_logs:/var/log/apache2
      # - /vagrant/site/index.html:/usr/local/apache2/htdocs/index.html
      # - /vagrant/site/script.py:/usr/local/apache2/htdocs/apache/script.py
    restart: always