version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /vagrant/Configs/Nginx/nginx.conf:/etc/nginx/nginx.conf
      - /vagrant/site:/usr/share/nginx/html/nginx
    restart: always