---
- name: Deploy services
  hosts: managers
  become: yes
  tasks:

    - name: Deploy Apache
      command: docker stack deploy --compose-file=/vagrant/Compose/apache_compose.yml apache

    - name: Deploy Nginx
      command: docker stack deploy --compose-file=/vagrant/Compose/nginx_compose.yml nginx

    - name: Deploy Prometheus
      command: docker stack deploy --compose-file=/vagrant/Compose/prometheus_compose.yml prometheus

    - name: Deploy Node-export and Cadvisor
      command: docker stack deploy --compose-file=/vagrant/Compose/node_cad_compose.yml nc

    - name: Deploy Grafana
      command: docker stack deploy --compose-file=/vagrant/Compose/grafana_compose.yml grafana

# - name: Deploy services
#   hosts: workers
#   become: yes
#   tasks:

#     - name: Deploy Apache
#       command: docker stack deploy --compose-file=/vagrant/Compose/apache_compose.yml apache

#     - name: Deploy Node-export and Cadvisor
#       command: docker stack deploy --compose-file=/vagrant/Compose/node_cad_compose.yml nc


