---
- name: Docker installation
  hosts: all
  become: yes
  tasks:

    - name: Install Docker and Docker Compose if not already installed
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
