---
- name: Deploy Nginx Docker Container
  hosts: managers
  become: yes
  tasks:

    - name: Pull Nginx Docker image
      docker_image:
        name: nginx
        source: pull

    - name: Create directory for nginx configuration
      file:
        path: /nginx_conf
        state: directory

    - name: Copy nginx configuration
      copy:
        src: /vagrant/Configs/Nginx/nginx.conf
        dest: /nginx_conf/nginx.conf

    - name: Create directory for nginx html
      file:
        path: /www
        state: directory

    - name: Copy index.html
      copy:
        src: /vagrant/site
        dest: /www

    # - name: Run Nginx container
    #   docker_container:
    #     name: nginx_container
    #     image: nginx
    #     state: started
    #     ports:
    #       - "80:80"
    #     volumes:
    #       - /nginx_conf/nginx.conf:/etc/nginx/nginx.conf
    #       - /www/site:/usr/share/nginx/html
    #     restart_policy: always
