---
- name: Deploy and Setup PostgreSQL Docker Container
  hosts: myhosts
  become: yes
  tasks:
    - name: Install psycopg2
      ansible.builtin.apt:
        name: python3-psycopg2
        state: present

    - name: Pull PostgreSQL Docker image
      docker_image:
        name: postgres
        source: pull

    - name: Run PostgreSQL container
      docker_container:
        name: postgres_container
        image: postgres
        env:
          POSTGRES_DB: dangerous_ip
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_INITDB_ARGS: "--data-checksums -c listen_addresses='*' -c hba_file='/var/lib/postgresql/data/pg_hba.conf'"
        ports:
          - "5432:5432"
        volumes:
          - /var/lib/postgresql/data
        restart_policy: always

    - name: Wait for PostgreSQL to be ready
      wait_for:
        port: 5432
        delay: 10
        timeout: 60

    - name: Check PostgreSQL connection
      community.general.postgresql_ping:
        login_user: user
        login_password: password
        login_db: dangerous_ip
      register: postgres_ping_result
      retries: 10
      delay: 10
      until: postgres_ping_result.failed == false

    - name: Create table for logging IP addresses
      community.general.postgresql_query:
        db: dangerous_ip
        login_user: user
        login_password: password
        query: |
          CREATE TABLE IF NOT EXISTS log_ips (
            id SERIAL PRIMARY KEY,
            ip_address VARCHAR(15) NOT NULL,
            timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            reason VARCHAR(255)
          )
      async: 120
      poll: 0

  handlers:
    - name: Reload PostgreSQL
      docker_container:
        name: postgres_container
        state: restarted
