name: Docker Testing
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  test:
    name: Test Docker Container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-docker-image -f Configs/Apache/Dockerfile .

    - name: Run tests
      run: docker run my-docker-image npm test
