name: Test installation packets
run-name: ${{ github.actor }} test GitHub Actions
on: [push]
jobs:
  installation-packets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set execute permission for installation.sh
        run: chmod +x Scripts/installation.sh
      - name: Run installation.sh script
        run: ./Scripts/installation.sh
